#!/bin/bash
# API Key Regeneration Helper Script
# Provides direct links to each provider's API key management page

set -e

echo "=========================================="
echo "API KEY REGENERATION HELPER"
echo "Date: $(date)"
echo "=========================================="
echo ""
echo "🔴 PROVIDERS REQUIRING KEY REGENERATION:"
echo ""
echo "1. 🔐 OPENROUTER"
echo "   Status: Valid key, needs credits"
echo "   URL: https://openrouter.ai/keys"
echo "   Action: Add payment method or use free models"
echo ""
echo "2. 🤗 HUGGINGFACE"
echo "   Status: Invalid/expired key"
echo "   URL: https://huggingface.co/settings/tokens"
echo "   Action: Generate new token with 'inference' scope"
echo ""
echo "3. 🚀 NVIDIA NIM"
echo "   Status: Invalid/expired key"
echo "   URL: https://build.nvidia.com/nim"
echo "   Action: Get API key for NIM endpoints"
echo ""
echo "4. 💎 GOOGLE GEMINI"
echo "   Status: Invalid/expired key"
echo "   URL: https://aistudio.google.com/app/apikey"
echo "   Action: Create new API key (free tier)"
echo ""
echo "5. 🌊 MISTRAL AI"
echo "   Status: Invalid/expired key"
echo "   URL: https://console.mistral.ai/api-keys"
echo "   Action: Generate new API key (free tier available)"
echo ""
echo "=========================================="
echo "🆕 NEW PROVIDERS TO ADD:"
echo "=========================================="
echo ""
echo "6. ⚡ GROQ (Recommended - Free)"
echo "   URL: https://console.groq.com/keys"
echo "   Benefits: Fast inference, free tier, reliable"
echo "   Models: Llama 3, Mixtral, Gemma"
echo ""
echo "7. 🤝 TOGETHER AI (Free Trial)"
echo "   URL: https://api.together.xyz/settings/api-key"
echo "   Benefits: 50+ models, $5 free credit"
echo "   Models: Llama, CodeLlama, Qwen, WizardLM"
echo ""
echo "8. 🎆 FIREWORKS AI ($1 Trial)"
echo "   URL: https://fireworks.ai/api-keys"
echo "   Benefits: Mixture of experts, low cost"
echo ""
echo "=========================================="
echo "📋 INSTRUCTIONS:"
echo "=========================================="
echo ""
echo "Step 1: Visit each URL above"
echo "Step 2: Generate a new API key"
echo "Step 3: Copy the key"
echo "Step 4: Edit .env file:"
echo "   nano $ENV_FILE"
echo ""
echo "Step 5: Update the corresponding line:"
echo "   ApiKey_openrouter=sk-or-your-new-key-here"
echo "   ApiKey_huggingface=hf_your-new-token-here"
echo "   etc."
echo ""
echo "Step 6: Save and exit"
echo ""
echo "Step 7: Re-run verification:"
echo "   cd /media/milosvasic/DATA4TB/Projects/LLM/LLMsVerifier/llm-verifier/cmd/model-verification"
echo "   go run ."
echo ""
echo "=========================================="
echo "💡 TIPS FOR SUCCESS:"
echo "=========================================="
echo ""
echo "✓ OpenRouter: Use free models like 'anthropic/claude-3-haiku'"
echo "✓ HuggingFace: Ensure 'inference' scope is enabled"
echo "✓ Google: Create separate keys for different projects"
echo "✓ Mistral: Start with 'mistral-small' (free), then upgrade"
echo "✓ Groq: No payment needed - just sign up and get key"
echo ""
echo "=========================================="
echo "📊 EXPECTED RESULTS AFTER REGENERATION:"
echo "=========================================="
echo ""
echo "Current: 1/42 models working (2.4%)"
echo "After fixes: 35-42 models working (83-100%)"
echo ""
echo "✨ Good luck! ✨"
echo ""
