// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/compare": {
            "post": {
                "description": "Compares multiple models based on task requirements",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Compare models",
                "parameters": [
                    {
                        "description": "Comparison request",
                        "name": "comparison",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Model comparison",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/analytics/cost": {
            "get": {
                "description": "Retrieves cost optimization analysis and recommendations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get cost analysis",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Time range in days (default: 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cost analysis data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/analytics/insights": {
            "get": {
                "description": "Retrieves usage insights and optimization recommendations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get usage insights",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Time range in days (default: 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usage insights",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/analytics/recommendations": {
            "post": {
                "description": "Retrieves AI-powered model recommendations based on task requirements",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get model recommendations",
                "parameters": [
                    {
                        "description": "Task requirements",
                        "name": "requirements",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analytics.TaskRequirements"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Model recommendations",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/analytics/trends": {
            "get": {
                "description": "Retrieves performance trend analysis with anomaly detection and forecasting",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get performance trends",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric name (e.g., response_time, throughput)",
                        "name": "metric",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Time range in hours (default: 24)",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Trend analysis data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/analytics/usage": {
            "get": {
                "description": "Retrieves usage pattern analysis including hourly/daily patterns and recommendations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get usage patterns",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Time range in days (default: 7)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usage analysis data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login response with JWT token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/export": {
            "post": {
                "description": "Exports system configuration in various formats for AI CLI tools",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Export configuration",
                "parameters": [
                    {
                        "description": "Export configuration",
                        "name": "export",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exported configuration",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Health status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues": {
            "get": {
                "description": "Retrieves system issues and problems with optional filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "issues"
                ],
                "summary": "Get issues",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by issue type",
                        "name": "issue_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of issues",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/models": {
            "get": {
                "description": "Retrieves a list of all LLM models with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Get models",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of results per page (default: 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by provider name",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by model status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of models",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new LLM model (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Create model",
                "parameters": [
                    {
                        "description": "Model data",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateModelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created model",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden (admin only)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/channels": {
            "get": {
                "description": "Returns the status and configuration of all available notification channels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Get notification channels status",
                "responses": {
                    "200": {
                        "description": "Channel statuses",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/subscribers": {
            "post": {
                "description": "Creates a new notification subscriber for specified event types and channels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Create notification subscriber",
                "parameters": [
                    {
                        "description": "Subscriber configuration",
                        "name": "subscriber",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Subscriber created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/test": {
            "post": {
                "description": "Sends a test notification to specified channels for testing purposes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Send test notification",
                "parameters": [
                    {
                        "description": "Test notification configuration",
                        "name": "test",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test notification sent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pricing": {
            "get": {
                "description": "Retrieves model pricing information with optional filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pricing"
                ],
                "summary": "Get pricing information",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by pricing model",
                        "name": "pricing_model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of pricing records",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new pricing record for a model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pricing"
                ],
                "summary": "Create pricing record",
                "parameters": [
                    {
                        "description": "Pricing information",
                        "name": "pricing",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreatePricingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created pricing record",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "description": "Retrieves scheduled jobs with optional filtering by type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedules",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by schedule type",
                        "name": "schedule_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of schedules",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new scheduled job for model verification or other tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Create schedule",
                "parameters": [
                    {
                        "description": "Schedule configuration",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created schedule",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/system/database-stats": {
            "get": {
                "description": "Returns database performance and size statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get database statistics",
                "responses": {
                    "200": {
                        "description": "Database statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Database not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/system/info": {
            "get": {
                "description": "Returns system version, statistics, and counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system information",
                "responses": {
                    "200": {
                        "description": "System information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analytics.TaskRequirements": {
            "type": "object",
            "properties": {
                "budget_limit": {
                    "description": "Maximum cost per request",
                    "type": "number"
                },
                "complexity": {
                    "description": "simple, medium, complex",
                    "type": "string"
                },
                "context_length": {
                    "description": "Required context window",
                    "type": "integer"
                },
                "required_features": {
                    "description": "json_mode, function_calling, etc.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "speed_requirement": {
                    "description": "fast, normal, quality_first",
                    "type": "string"
                },
                "task_type": {
                    "description": "coding, writing, analysis, etc.",
                    "type": "string"
                }
            }
        },
        "api.CreateModelRequest": {
            "type": "object",
            "required": [
                "model_id",
                "name",
                "provider_id"
            ],
            "properties": {
                "architecture": {
                    "type": "string",
                    "maxLength": 100
                },
                "code_capability_score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "context_window_tokens": {
                    "type": "integer",
                    "minimum": 0
                },
                "deprecated": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "feature_richness_score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "is_multimodal": {
                    "type": "boolean"
                },
                "language_support": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_output_tokens": {
                    "type": "integer",
                    "minimum": 0
                },
                "model_id": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "open_source": {
                    "type": "boolean"
                },
                "overall_score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "parameter_count": {
                    "type": "integer",
                    "minimum": 0
                },
                "provider_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "release_date": {
                    "type": "string"
                },
                "reliability_score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "responsiveness_score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "supports_audio": {
                    "type": "boolean"
                },
                "supports_reasoning": {
                    "type": "boolean"
                },
                "supports_video": {
                    "type": "boolean"
                },
                "supports_vision": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "training_data_cutoff": {
                    "type": "string"
                },
                "use_case": {
                    "type": "string",
                    "maxLength": 200
                },
                "value_proposition_score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "verification_status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "verified",
                        "failed"
                    ]
                },
                "version": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "api.CreatePricingRequest": {
            "type": "object",
            "required": [
                "currency",
                "input_token_cost",
                "model_id",
                "output_token_cost",
                "pricing_model"
            ],
            "properties": {
                "cached_input_token_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "currency": {
                    "type": "string",
                    "maxLength": 3,
                    "minLength": 3
                },
                "effective_from": {
                    "type": "string"
                },
                "effective_to": {
                    "type": "string"
                },
                "input_token_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "model_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "output_token_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "pricing_model": {
                    "type": "string"
                },
                "request_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "storage_cost": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "api.CreateScheduleRequest": {
            "type": "object",
            "required": [
                "name",
                "schedule_type",
                "target_type"
            ],
            "properties": {
                "cron_expression": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "interval_seconds": {
                    "type": "integer",
                    "minimum": 60
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_runs": {
                    "type": "integer",
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "schedule_type": {
                    "type": "string"
                },
                "target_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "target_type": {
                    "type": "string"
                }
            }
        },
        "api.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
